name = "myneuralgia-queue-consumer"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "myneuralgia-cms"
database_id = "a00d2161-cc39-4bdc-a78f-7a524ff49b96"

[[queues.consumers]]
queue = "translation-queue"
max_batch_size = 1
max_retries = 5
dead_letter_queue = "translation-dlq"

[ai]
binding = "AI"

[vars]
TARGET_REPO = "airon1337/myneuralgia"
TARGET_FOLDER = "content/en"
AI_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"
