media:
  input: zdjecia
  output: /zdjecia

content:
  - name: artykuly
    label: Artykuły
    type: collection
    path: artykuly
    format: yaml-frontmatter
    filename:
      template: '{fields.tytul}.md'
      field: create
    view:
      fields: [tytul, data]
      primary: tytul
      sort: [data, tytul]
      default:
        sort: data
        order: desc
    fields:
      - name: tytul
        label: Tytuł
        type: string
        required: true
      - name: data
        label: Data i godzina publikacji
        type: date
        description: "Ustaw przyszłą datę i godzinę, aby zaplanować publikację (np. 2026-06-25T18:00). Artykuł pojawi się automatycznie po nadejściu tego terminu."
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm
        required: true
      - name: obraz
        label: Okładka (zdjęcie)
        type: image
        required: false
      - name: body
        label: Treść artykułu
        type: rich-text
